name: first_flutter_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.19.0
  carousel_slider:
    git: https://github.com/serenader2014/flutter_carousel_slider

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
